name: Build STM32 Toolchain

on:
  push:
    branches:
      - 13.3.rel1
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Free disk space
        run: |
          sudo apt-get remove -y \
            '^dotnet-.*' \
            '^llvm-.*' \
            'php.*' \
            azure-cli \
            google-chrome-stable \
            firefox \
            powershell \
            mono-devel \
            || true
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf \
            /usr/share/dotnet \
            /usr/local/lib/android \
            /opt/ghc \
            /opt/hostedtoolcache/CodeQL
          df -h

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            yacc \
            flex \
            gcc-arm-none-eabi \
            gdb-multiarch \
            cmake \
            git \
            openocd \
            python3 \
            python3-pip \
            python3-venv \
            texi2html \
            texinfo \
            automake
          test -f /usr/bin/aclocal-1.16
          test -f /usr/bin/automake-1.16
          sudo ln -s /usr/bin/aclocal-1.16 /usr/bin/aclocal-1.15
          sudo ln -s /usr/bin/aclocal-1.16 /usr/bin/aclocal-1.14
          sudo ln -s /usr/bin/automake-1.16 /usr/bin/automake-1.15
          sudo ln -s /usr/bin/automake-1.16 /usr/bin/automake-1.14
